# Generated by Django 3.0.4 on 2020-04-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_store_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_news',
            name='time_of_post',
            field=models.DateField(auto_now=True),
        ),
    ]
